on:
  pull_request: # Run this action when push event triggers.
    branches: # Run this action on specified branches
      - tests/BackstopJSAction
      - develop
      - master
      - visualtest/pooja

name: Run BackstopJS test cases # Name of the action
jobs:
  Run-BackstopJS-TestCase:
    name: Run BackstopJS test Case #
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v2
      with:
       ref: ${{ github.event.pull_request.head.sha }}
     
    - name: Checkout base
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.base.ref }}
        path: base

    - name: Current directory and listings
      run: |
           pwd
           ls -al
    - name: Install and config site
      uses: docker://rtcamp/base-wo:v1.0.0
      env:
        RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
            
    - name: Archive HTML Report on failure
      if: failure()
      uses: actions/upload-artifact@v1
      with:
        name: report
        path: ./tests/visual-tests/test/backstop_data/
    - name: Cleanup
      if: ${{ always() }}
      uses: rtCamp/action-cleanup@master
